language: perl

perl:
  - "5.26"
  - "5.24"
  - "5.8"

before_install:
  - cpanm DBI
  - cpanm Exporter
  - cpanm lib
  - cpanm DBD::SQLite
  - cpanm Test::Kwalitee

install:
  cpanm --quiet --installdeps --notest .

